prefix  = "dev"
region = "eu-west-1"
amis = "ami-07d9160fa81ccffb5"


vpc_name = "acloudguruVPC"
vpc_cidr = "10.0.0.0/16"
vpc_assign_generated_ipv6_cidr_block = "true"
vpc_subnet_public = "10.0.1.0 - eu-west-1a"
vpc_subnet_private = "10.0.2.0 - eu-west-1b"
vpc_subnet_private_cidr = "10.0.2.0/24"
vpc_subnet_public_cidr = "10.0.1.0/24"
vpc_igw = "MyIGW"
availability_zones_public = "eu-west-1a"
availability_zones_private = "eu-west-1b"
vpc_route_public = "MyPublicRoute"
vpc_destination_cidr_block = "0.0.0.0/0"
instance_name1 = "WebServer01"
instance_name2 = "MyDBServer"
vpc_security_group = "WebDMZ"
vpc_security_group2 = "MyDBSG"
key_name = "MyNewKP"
